name: Add SSH Key
on:
  workflow_dispatch:
  push:
    branches: [main]
jobs:
  add-key:
    runs-on: ubuntu-latest
    steps:
      - name: Add SSH key and restart PM2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 141.94.10.182
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICNsX4vDUoZdv4BzCpvlkZ75G6NcmZugIAU3xr8zyzVh karim.b@PRECISION-PC12" >> ~/.ssh/authorized_keys
            sort -u ~/.ssh/authorized_keys -o ~/.ssh/authorized_keys
            pm2 restart amilo || true
            echo "Done!"
